New handler for either include files or program files
camfort/fortran-src-extras pull request #4
Opened 2022-06-15 16:17 UTC by RaoulHC

Handler that takes advantage of camfort/fortran-src#227.

2022-06-16 16:52 UTC, raehik requested changes

2022-06-16 16:52 UTC, raehik commented on src/Language/Fortran/Extras.hs
> +  (srcOptions, toolOptions) <-
Nag: bit clearer as `RunOptions srcOptions toolOptions <- getRunOptions desc header optsParser` (or by binding then extracting manually)

2022-06-16 16:58 UTC, raehik commented
I tend to throw Git repo references into `stack.yaml` when trying to use code that isn't yet on Hackage. Like so:

```yaml
resolver: nightly-2022-03-30
packages: [.]

extra-deps:
# not yet released :<
- git: https://github.com/nikita-volkov/refined
  commit: 91566f4e313937b7315a401fd116fa0aa2a15f06
```

Adding a clause for fortran-src would fix the CI while a Hackage release is pending (there's similar syntax for Cabal). I can add that to this PR or after merge.

2022-06-16 17:00 UTC, raehik commented on src/Language/Fortran/Extras.hs
> +  (srcOptions, toolOptions) <-
I learned how to do suggested changes lol

2022-06-16 17:01 UTC, raehik commented on src/Language/Fortran/Extras.hs
> +    (fortranSrcOpts &&& toolOpts) <$> getRunOptions desc header optsParser
Nag: bit clearer with pattern matching (or by binding then extracting manually). Arrow import probably unused with this.

```suggestion
  RunOptions srcOptions toolOptions <- getRunOptions desc header optsParser
```

2022-06-17 12:45 UTC, RaoulHC commented on src/Language/Fortran/Extras.hs
> +    (fortranSrcOpts &&& toolOpts) <$> getRunOptions desc header optsParser
Changed to this, probably should have seen this rather than reaching for arrows 😅

2022-06-17 13:02 UTC, raehik commented
Cheers, I'll merge this!

2022-06-17 13:02 UTC, merged

2022-06-17 13:04 UTC, RaoulHC commented
Looks like the cabal test was still failing, does something else need to be added for that?

2022-06-17 13:07 UTC, raehik commented
yeah, easiest to merge and copy over config from another project - done in latest commit https://github.com/camfort/fortran-src-extras/commit/7caee0797b35bcc65d0fa7f74c77e797567a573c